# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0004_added_production_for_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_energy_cost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='colony',
            name='energy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='production',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building_production', to='goods.Stock'),
        ),
    ]
