# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0005_add_building_energy_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='production_energy',
            field=models.SmallIntegerField(default=0),
        ),
    ]
