# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0006_add_building_energy_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Building Properties',
            },
        ),
        migrations.CreateModel(
            name='BuildingPropertyAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony.Building')),
                ('building_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony.BuildingProperty')),
            ],
            options={
                'verbose_name_plural': 'Building Properties',
            },
        ),
        migrations.AddField(
            model_name='buildingassignment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='building',
            name='building_properties',
            field=models.ManyToManyField(through='colony.BuildingPropertyAssignment', to='colony.BuildingProperty'),
        ),
        migrations.AlterUniqueTogether(
            name='buildingpropertyassignment',
            unique_together=set([('building', 'building_property')]),
        ),
    ]
