# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0007_building_properties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingpropertyassignment',
            options={},
        ),
        migrations.AddField(
            model_name='colony',
            name='residents',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
